[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
edition = "2024"
license = "Apache-2.0"
version = "0.1.0"

[workspace.dependencies]
gpui-kit = { version = "=0.7.0", features = ["tree-sitter-languages"] }
gix = { version = "0.88", default-features = false, features = ["sha1", "max-performance-safe", "revision", "blob-diff", "index", "status", "mailmap"] }
anyhow = "1"
notify = "8"
rayon = "1"
imara-diff = "0.2"
regex = "1"
futures = { version = "0.3", features = ["executor"] }
thiserror = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
clap = { version = "4", features = ["derive"] }
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
rsit-graph = { path = "crates/rsit-graph" }
rsit-git = { path = "crates/rsit-git" }
rsit-log = { path = "crates/rsit-log" }
rsit-index = { path = "crates/rsit-index" }
rsit-diff = { path = "crates/rsit-diff" }

[profile.dev.package."*"]
opt-level = 2
