[package]
name = "rsit-log"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
gix.workspace = true
rsit-git.workspace = true
rsit-graph.workspace = true
notify.workspace = true
futures.workspace = true
rsit-index.workspace = true
rayon.workspace = true
regex.workspace = true

[dev-dependencies]
tempfile = "3"
