[package]
name = "rsit-app"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
path = "src/lib.rs"

[[bin]]
name = "rsit"
path = "src/main.rs"

[dependencies]
gpui-kit.workspace = true
anyhow.workspace = true
clap.workspace = true
chrono.workspace = true
gix.workspace = true
rsit-graph.workspace = true
rsit-git.workspace = true
rsit-log.workspace = true
futures.workspace = true

[dev-dependencies]
gpui-kit = { workspace = true, features = ["test-support"] }
tempfile = "3"
